### ISSUE TITLE
Concurrent get_mut()s of different keys?

### ISSUE THREAD

**Issue by willglynn** [adevore/rudy#12]
`specs` has a [`DistinctStorage` marker trait](https://slide-rs.github.io/specs-website/docs/docs/master/specs/trait.DistinctStorage.html) which guarantees that:

> Multiple threads may call `get_mut()` with distinct indices without causing undefined behavior.

Now, yes: `get_mut()` itself takes a `&mut self`, and there's various barriers in the way of getting a `&mut RudyMap` to another thread, like how `std::thread::spawn()` needs `'static`. There's even more barriers for getting a `&mut RudyMap` to multiple threads, since… well, the whole purpose of `&mut`s is to be exclusive. Having said that, achieving parallelism by splitting the keyspace is useful in practice and can often be accommodated by generic containers even if the compiler doesn't understand, so the `DistinctStorage` trait here is `unsafe` and asks implementors to prove its safety.

As I understand it, safe concurrent `get_mut()` requires two things:

1. An `Option<&mut>` returned by `get_mut()` of one key must not overlap with any `Option<&mut>` returned for any other key. That is, each key's `&mut` must refer to an entirely disjoint set of bytes.
2. `get_mut()` on one key does not write to any memory location that is read by `get_mut()` on any other key.

The `specs` use case defers insertions/removals to outside the parallel section, so it really is just `get_mut()` that's under examination.

My read of the Rudy code is that `get_mut()` can never trigger any internal reorganization or anything like that, so any memory writes would be caused by the caller acting on the `&mut` element -- and that while keys have essentially shared storage, elements do not. `RudyMap` would therefore seem to satisfy the `specs::DistinctStorage` guarantee.

Do you agree with this analysis? If concurrent `get_mut()`s are in fact safe today, is this a contract Rudy is willing to uphold going forward?

**Comment by adevore** [comment]
Yes, I agree with your analysis. I am willing to commit to maintaining the contract. There are access optimizations that cause internal mutation that I may implement in the future, but these will not interfere with the memory locations of the returned Option<&mut V>

**Comment by willglynn** [comment]
That's why I snuck in that last question :-) What kind of internal mutations are you thinking of adding down the road? Unsynchronized concurrent modification of Rudy internals seems like a recipe for UB, preventing even mutations that would be completely safe given a usual `&mut self`.

Would it make sense to add an `unsafe fn get_mut_concurrent(&mut self, key: K)` that maintains and documents this distinct keys concurrency guarantee, allowing `get_mut()` to eventually diverge?

**Comment by adevore** [comment]
The reference Judy array implementation caches lookups when using the JPM (Judy Population Manager). I am reluctant to implement that particular optimization for the exact reasons you mention. It would require endangering a lot of the guarantees of Rust for uncertain gain.

A separate method is not necessary. None of the optimizations in the reference implementation violate the guarantee. I can't think of any optimization opportunities that would cause a violation.

**Comment by willglynn** [comment]
Sounds great, thanks!
