### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by willglynn** [adevore/rudy#18]
`rudy-0.0.1` exists as a crate, and I think it might be cb50da58cdcf6e0f54eb32042fabecb770504fd7,  but without a `0.0.1` tag I can't quickly jump to that point in the repo.

`rudy` should have tags for each release.

- [x] Identify and tag 0.0.1 retroactively
- [x] Decide on how to integrate tags into a release process ([`cargo release`](https://github.com/sunng87/cargo-release)?)

**Comment by adevore** [comment]
0.0.1 has now been tagged (you were correct). I will look into cargo-release.

**Comment by adevore** [comment]
Everything worked well with cargo release. I'll definitely use it in the future.
